# Generated by Django 4.1.2 on 2022-11-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('E', 'Empleado'), ('C', 'Cliente')], max_length=1, null=True),
        ),
    ]
