# Generated by Django 4.1.2 on 2022-11-26 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_user_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='date_contract',
            new_name='fecha_contrato',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('C', 'Cliente'), ('E', 'Empleado')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
