# Generated by Django 4.1.2 on 2022-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_rename_date_contract_empleado_fecha_contrato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('Permiso_Empleado', 'tiene acceso a CRUD de datos'), ('Permiso_Cliente', 'tiene acceso a vistas basicas'))},
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('E', 'Empleado'), ('C', 'Cliente')], max_length=1, null=True),
        ),
    ]
