# Generated by Django 4.1.3 on 2022-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_user_options_alter_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('C', 'Cliente'), ('E', 'Empleado')], max_length=1, null=True),
        ),
    ]
