# Generated by Django 4.1.2 on 2022-11-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('D', 'Disponible'), ('N', 'No Disponible'), ('P', 'En prestamo')], max_length=1),
        ),
    ]
