# Generated by Django 4.1.3 on 2022-11-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0003_libro_descripcion_alter_libro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='home.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('D', 'Disponible'), ('N', 'No Disponible'), ('P', 'En prestamo')], max_length=1),
        ),
    ]
