# Generated by Django 4.1.2 on 2022-11-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_libro_imagen_alter_libro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('N', 'No Disponible'), ('D', 'Disponible'), ('P', 'En prestamo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(upload_to='libros'),
        ),
    ]
