# Generated by Django 4.1.2 on 2022-11-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0004_alter_user_options_alter_user_tipo'),
        ('Libros', '0005_alter_libro_estado_alter_libro_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.empleado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.libro')),
            ],
            options={
                'verbose_name': 'prestamo',
                'verbose_name_plural': 'prestamos',
            },
        ),
    ]
